/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#f7f9fe',
        'surface-bright': '#f7f9fe',
        'surface-dim': '#d7dadf',
        'surface-container': '#ebeef3',
        'surface-container-low': '#f1f4f9',
        'surface-container-high': '#e5e8ed',
        'surface-container-highest': '#dfe3e8',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#dfe3e8',
        'surface-tint': '#436182',
        'on-surface': '#181c20',
        'on-surface-variant': '#43474d',
        'primary': '#002542',
        'primary-container': '#1b3b5a',
        'primary-fixed': '#d1e4ff',
        'primary-fixed-dim': '#abc9ef',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001d35',
        'on-primary-fixed-variant': '#2a4968',
        'on-primary-container': '#87a5ca',
        'secondary': '#545f72',
        'secondary-container': '#d5e0f7',
        'secondary-fixed': '#d8e3fa',
        'secondary-fixed-dim': '#bcc7dd',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#111c2c',
        'on-secondary-fixed-variant': '#3c475a',
        'on-secondary-container': '#586377',
        'tertiary': '#002a17',
        'tertiary-container': '#004227',
        'tertiary-fixed': '#9ff5c1',
        'tertiary-fixed-dim': '#83d8a6',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#002111',
        'on-tertiary-fixed-variant': '#005231',
        'on-tertiary-container': '#5fb384',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'outline': '#73777e',
        'outline-variant': '#c3c6ce',
        'inverse-surface': '#2d3135',
        'inverse-on-surface': '#eef1f6',
        'inverse-primary': '#abc9ef',
        'background': '#f7f9fe',
        'on-background': '#181c20',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
